---
config:
  theme: redux
---
%%{init: {
  'themeVariables': {
    'fontSize': '20px',
    'nodeBorder': '#333'
  }
}}%%
graph LR
    subgraph pipeline["Data Pipeline"]
        A["INICIO"] --> A1{"main: Cargar Configuración"};
        A1 --> B("setup_logging: Configurar Logger");
        B --> C{"setup_environment: Iniciar Sesión Spark"};
        
        C --> D{"read_data: Leer Datos con Esquema Explícito"};
        
        D --> E{"data_quality_input: Validar DQ de ENTRADA"};
        
        E -->|FALLO| Z("ERROR: Detener Pipeline");
        
        E -->|APROBADO| F{"transform_data: Iniciar Transformaciones"};

        subgraph trans["Transformaciones y Reglas de Negocio"]
            F --> F1("Eliminar Duplicados y Formatear Fecha");
            F1 --> F2("date_filter: Filtrar por Fechas");
            F2 --> F3("country_filter: Filtrar por País");
            F3 --> F4("delivery_filter: Filtrar por Tipo de Entrega");
            F4 --> F5("derived_cols: Crear Col. Indicador");
            F5 --> F6("fix_nulls: Rellenar Valores Nulos");
            F6 --> F7("treatment_units: Estandarizar Unidades/Precios");
            F7 --> F8("Calcular Columna Total");
            F8 --> F9("rename_and_order_cols: Renombrar y Ordenar Columnas");
        end

        F9 --> G{"data_quality_output: Validar DQ de SALIDA"};
        
        G -->|FALLO| Z;
        
        G -->|APROBADO| H{"write_data: Escribir Data Particionada (Parquet)"};
        
        H --> I("FIN: Detener Sesión Spark");

        Z --> I;
    end